### ISSUE TITLE
NameError on the "Cartola  FC - Data Analysis" notebook

### ISSUE THREAD

**Issue by AntLouiz** [jamesperes/CartolaFC#5]
Hey @jamesperes this notebook have a **NameError**:

![image](https://user-images.githubusercontent.com/17905026/47510132-e02e1d00-d84d-11e8-9f37-b8e886ae6004.png)

I suggest to change the line:
`pontuacao_final = resultado_final.groupby(['Nome', 'Clube', 'Posicao'], as_index=False)['Pontos'].sum()`

to

`pontuacao_final = resultados.groupby(['Nome',** 'Clube', 'Posicao'], as_index=False)['Pontos'].sum()`

**Comment by jamesperes-zz** [comment]
fixed in #6
